/**
 * Netlify Function — og.js
 * Stable OG endpoint for /share/:slug
 */
const SUPABASE_URL='https://hozlyddiqodvjguqywty.supabase.co';
const SITE_URL='https://www.selogercm.com';
const DEFAULT_OG_IMAGE='https://hozlyddiqodvjguqywty.supabase.co/storage/v1/object/public/listing-images/listings/listing_1776010205589/photo_0_1776010205589.webp';
function e(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function price(v,m){const a=Number(v||0).toLocaleString('fr-FR')+' FCFA';return m==='sale'?a:a+'/mois'}
function slug(event){const raw=event.rawUrl||'';const path=event.path||'';return decodeURIComponent((raw.match(/\/share\/([^/?#]+)/)?.[1]||path.match(/\/share\/([^/?#]+)/)?.[1]||event.queryStringParameters?.slug||'').trim())||null}
function abs(u){if(!u) return DEFAULT_OG_IMAGE;u=String(u);if(u.startsWith('https://')) return u;if(u.startsWith('http://')) return u.replace('http://','https://');if(u.startsWith('/')) return SITE_URL+u;return SITE_URL+'/'+u}
exports.handler=async(event)=>{const SB_KEY=process.env.SB_ANON_KEY;const s=slug(event);const canon=s?`${SITE_URL}/annonce/${s}`:`${SITE_URL}/annonces`;if(!SB_KEY||!s)return resp(html('SE LOGER CM','Trouvez votre bien immobilier à Douala et au Cameroun.',DEFAULT_OG_IMAGE,canon));try{const api=`${SUPABASE_URL}/rest/v1/listings?slug=eq.${encodeURIComponent(s)}&select=title,description,price,rent_sale,city,district,images&limit=1`;const r=await fetch(api,{headers:{apikey:SB_KEY,Authorization:`Bearer ${SB_KEY}`,Accept:'application/json'}});if(!r.ok) throw new Error('api');const arr=await r.json();const ad=arr[0];if(!ad) throw new Error('none');const t=e(ad.title||'Annonce immobilière');const d=e([price(ad.price,ad.rent_sale),[ad.district,ad.city].filter(Boolean).join(', '),(ad.description||'Disponible sur SE LOGER CM').replace(/\s+/g,' ').slice(0,120)].filter(Boolean).join(' · '));const img=e(abs(Array.isArray(ad.images)&&ad.images[0]?ad.images[0]:DEFAULT_OG_IMAGE));return resp(html(t,d,img,canon));}catch(err){return resp(html('Annonce immobilière','Annonce immobilière sur SE LOGER CM.',DEFAULT_OG_IMAGE,canon));}};
function resp(body){return {statusCode:200,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache, no-store, must-revalidate'},body}}
function html(title,desc,img,url){return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>${title} | SE LOGER CM</title><meta name="description" content="${desc}"><meta name="robots" content="noindex,nofollow"><meta property="og:type" content="article"><meta property="og:site_name" content="SE LOGER CM"><meta property="og:locale" content="fr_CM"><meta property="og:url" content="${e(url)}"><meta property="og:title" content="${title} | SE LOGER CM"><meta property="og:description" content="${desc}"><meta property="og:image" content="${img}"><meta property="og:image:secure_url" content="${img}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${title} | SE LOGER CM"><meta name="twitter:description" content="${desc}"><meta name="twitter:image" content="${img}"><link rel="canonical" href="${e(url)}"></head><body><p><a href="${e(url)}">Voir l'annonce</a></p></body></html>`}
