[[redirects]]
  from = "/share/*"
  to = "/annonce/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/share"
  to = "/share/"
  status = 301

[[headers]]
  for = "/share/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"